[package]
name = "sotf-wgpu-macros"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Macros for wgpu"
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
license.workspace = true
rust-version.workspace = true
exclude = ["Cargo.lock"]

[lib]
name = "wgpu_macros"
proc-macro = true

[dependencies]
heck.workspace = true
quote.workspace = true
syn = { workspace = true, features = ["full"] }

[package.metadata.release]
tag-name = "{{crate_name}}-v{{version}}"
