[package]
name = "sotf-message-custom-buttons"
publish = false
version = "0.1.0"
edition = "2021"

[dependencies]
rfd = { version = "0.17.2", package = "sotf-rfd", path = "../..", features = ["common-controls-v6"] }

[build-dependencies]
embed-resource = "3"

[[bin]]
name = "message-custom-buttons"
path = "src/main.rs"
