[package]
name = "gpui-toolkit-gpui-macros"
version = "0.1.0"
edition = "2024"
description = "Macros used by gpui"
license = "Apache-2.0"
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
name = "gpui_macros"
path = "src/gpui_macros.rs"
proc-macro = true
doctest = true

[features]
inspector = []

[dependencies]
heck = "0.5"
proc-macro2 = "1.0.93"
quote = "1.0.9"
syn = { version = "3.0.4", features = ["full", "extra-traits", "visit-mut"] }

[dev-dependencies]
gpui = { package = "gpui-toolkit-gpui", path = "../gpui", features = ["inspector"] }
