[package]
name = "sotf-vst3-com"
version = "0.1.0"
authors = ["Microsoft Corp.", "Mike Hilgendorf"]
description = """
Fork of com-rs
"""
edition = "2018"
license = "MIT"
readme = "./README.md"

[lib]
name = "vst3_com"

[dependencies]
vst3-com-macros = { version = "0.2.0", package = "sotf-vst3-com-macros", path = "macros" }

[package.metadata.release]
tag-name = "{{crate_name}}-v{{version}}"
