[package]
name = "gpui-toolkit-perf"
version = "0.1.0"
edition = "2024"
description = "A tool for measuring Zed test performance, with too many Clippy lints"
license = "Apache-2.0"
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
name = "perf"

[dependencies]
collections = { workspace = true }
serde = { version = "1.0.221", features = ["derive", "rc"] }
serde_json = { version = "1.0.144", features = ["preserve_order", "raw_value"] }
