[package]
name = "sotf-test-tflite"
publish = false
version = "0.1.0"
edition = "2024"

[lib]
name = "test_tflite"

[dependencies]

[build-dependencies]
home.workspace = true
lazy_static.workspace = true
regex.workspace = true
infra = { version = "0.1.0", package = "sotf-infra", path = "../infra" }
tract-core.workspace = true
suite-onnx = { version = "0.1.0", package = "sotf-suite-onnx", path = "../suite-onnx" }
suite-unit = { version = "0.1.0", package = "sotf-suite-unit", path = "../suite-unit" }

[dev-dependencies]
home.workspace = true
regex.workspace = true
lazy_static.workspace = true
log.workspace = true
tflitec.workspace = true
tract-core.workspace = true
tract-tflite.workspace = true
tract-onnx-opl.workspace = true
infra = { version = "0.1.0", package = "sotf-infra", path = "../infra" }
suite-onnx = { version = "0.1.0", package = "sotf-suite-onnx", path = "../suite-onnx" }
suite-unit = { version = "0.1.0", package = "sotf-suite-unit", path = "../suite-unit" }
