[package]
name = "gpui-toolkit-scheduler"
version = "0.1.0"
edition = "2024"
description.workspace = true
license = "Apache-2.0"
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
name = "scheduler"
path = "src/scheduler.rs"
doctest = false

[features]
test-support = []

[dependencies]
async-task = "4.7"
backtrace = "0.3"
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3.32"
parking_lot = "0.12.1"
rand = "0.9"
web-time = "1.1.0"
