[package]
name = "sotf-wgpu-example-custom-backend"
edition = "2021"
rust-version = "1.87"
publish = false

[features]
default = ["web"]
web = ["wgpu/web"]

[dependencies]
wgpu = { package = "sotf-wgpu", path = "../../../wgpu", version = "29.0.0", features = [
    "custom",
    "wgsl",
], default-features = false }
pollster = { version = "0.4", features = ["macro"] }

[[bin]]
name = "wgpu-example-custom-backend"
path = "src/main.rs"
