["package"]
"name" = "sotf-media"
"version" = "0.1.0"
"edition" = "2024"
"license" = "Apache-2.0"
"description" = "Bindings to macos media handling APIs for Zed"

["lints"]

["lints"."rust"]

["lints"."rust"."unexpected_cfgs"]
"level" = "allow"

["lints"."clippy"]
"dbg_macro" = "deny"
"todo" = "deny"
"declare_interior_mutable_const" = "deny"
"redundant_clone" = "deny"
"disallowed_methods" = "deny"
"type_complexity" = "allow"
"let_underscore_future" = "allow"
"single_range_in_vec_init" = "allow"
"too_many_arguments" = "allow"
"large_enum_variant" = "allow"
"nonminimal_bool" = "allow"

["lints"."clippy"."style"]
"level" = "allow"
"priority" = -1

["lib"]
"name" = "media"
"path" = "src/media.rs"
"doctest" = false

["dependencies"]

["dependencies"."anyhow"]
"version" = "1.0.86"

["target"]

["target"."cfg(target_os = \"macos\")"]

["target"."cfg(target_os = \"macos\")"."dependencies"]
"foreign-types" = "0.5"

["target"."cfg(target_os = \"macos\")"."dependencies"."core-foundation"]
"version" = "=0.10.1"

["target"."cfg(target_os = \"macos\")"."dependencies"."ctor"]
"version" = "1.0.6"

["target"."cfg(target_os = \"macos\")"."dependencies"."metal"]
"version" = "0.33"

["target"."cfg(target_os = \"macos\")"."dependencies"."core-video"]
"version" = "0.5.2"
"features" = ["metal"]

["target"."cfg(target_os = \"macos\")"."dependencies"."objc"]
"version" = "0.2"

["target"."cfg(target_os = \"macos\")"."build-dependencies"]
"bindgen" = "0.72.1"

[package.metadata.release]
tag-name = "{{crate_name}}-v{{version}}"
