[package]
name = "gpui-toolkit-gpui-windows"
version = "0.1.2"
edition.workspace = true
description.workspace = true
license = "Apache-2.0"
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[lib]
name = "gpui_windows"
path = "src/gpui_windows.rs"

[features]
default = ["gpui/default"]
test-support = ["gpui/test-support"]
screen-capture = ["gpui/screen-capture", "scap"]

[dependencies]
gpui.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
anyhow.workspace = true
collections.workspace = true
etagere = "0.2"
futures.workspace = true
image.workspace = true
itertools.workspace = true
log.workspace = true
parking_lot.workspace = true
rand.workspace = true
raw-window-handle = "0.6"
smallvec.workspace = true
util.workspace = true
uuid.workspace = true
windows.workspace = true
windows-core.workspace = true
windows-numerics = "0.3"
windows-registry = "0.6"

[target.'cfg(target_os = "windows")'.dependencies.scap]
workspace = true
optional = true

[target.'cfg(target_os = "windows")'.build-dependencies]
windows-registry = "0.6"
