[package]
name = "sotf-tract-transformers"
version = "0.22.4"
license = "MIT OR Apache-2.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>", "Louis Chouraki <louis.chouraki@sonos.com>"]
description = "Tiny, no-nonsense, self contained, TensorFlow and ONNX inference"
repository = "https://github.com/pierreaubert/sotf-3rdparties"
keywords = [ "TensorFlow", "NeuralNetworks", "Transformers" ]
categories = [ "science" ]
autobenches = false
edition = "2024"
rust-version = "1.85"
include = [ "Cargo.toml", "src/**/*.rs", "LICENSE*" ]

[lib]
name = "tract_transformers"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
tract-nnef.workspace = true

[package.metadata.release]
tag-name = "{{crate_name}}-v{{version}}"
