[package]
name = "sotf-async-task"
# When publishing a new version:
# - Update CHANGELOG.md
# - Create "v4.x.y" git tag
version = "4.7.1"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
edition = "2021"
rust-version = "1.57"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/pierreaubert/sotf-3rdparties"
description = "Task abstraction for building executors"
keywords = ["futures", "task", "executor", "spawn"]
categories = ["asynchronous", "concurrency", "no-std"]
exclude = ["/.*"]

[lib]
name = "async_task"

[features]
default = ["std"]
std = []

[dependencies]
# Uses portable-atomic polyfill atomics on targets without them
portable-atomic = { version = "1", optional = true, default-features = false }

[dev-dependencies]
atomic-waker = "1"
easy-parallel = "3"
flaky_test = "0.2"
flume = { version = "0.12", default-features = false }
futures-lite = "2.0.0"
once_cell = "1"
pin-project-lite = "0.2.10"
smol = "2"

[package.metadata.release]
tag-name = "{{crate_name}}-v{{version}}"
