[package]
name = "sotf-xim-ctext"
description = "compound text en/decoder"
version = "0.3.0"
authors = ["Riey <creeper844@gmail.com>"]
repository = "https://github.com/pierreaubert/sotf-3rdparties"
edition = "2018"
license = "MIT"
rust-version = "1.61"

[lib]
name = "xim_ctext"

[dependencies]
encoding_rs = "0.8.28"

[features]
default = ["std"]
std = []

[[bin]]
name = "xim-ctext"
path = "src/main.rs"

[package.metadata.release]
tag-name = "{{crate_name}}-v{{version}}"
