[package]
name = "sotf-hlsl-snapshots"
description = "HLSL snapshot data shared by Naga tests"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "hlsl_snapshots"
path = "src/lib.rs"
test = false

[dependencies]
anyhow.workspace = true
nanoserde.workspace = true

[package.metadata.release]
tag-name = "{{crate_name}}-v{{version}}"
