[package]
name = "sotf-cost_model"
publish = false
version = "0.20.7-pre"
edition = "2024"

[workspace]
members = []

[dependencies]
lazy_static = "1.4.0"
clap = "3.0.7"
scan_fmt = "0.2.6"
rand = "0.8.4"
colorous = "1.0.6"
nu-ansi-term = "0.50"
pbr = "1"
readings-probe = "0.1.4"
tract-linalg = { version = "0.22.4", package = "sotf-tract-linalg", path = ".."}
tract-data = { version = "0.22.4", package = "sotf-tract-data", path = "../../data" }

[[bin]]
name = "cost_model"
path = "src/main.rs"
