[package]
name = "librespot-oauth"
version = "0.8.0"
rust-version.workspace = true
authors = ["Nick Steel <nick@nsteel.co.uk>"]
license.workspace = true
description = "OAuth authorization code flow with PKCE for obtaining a Spotify access token"
repository.workspace = true
edition.workspace = true

[features]
# Refer to the workspace Cargo.toml for the list of features
default = ["native-tls"]

# TLS backends (mutually exclusive - compile-time checks in src/lib.rs)
native-tls = ["reqwest/native-tls"]
rustls-tls-native-roots = [
    "__rustls",
    "reqwest/rustls",
]
rustls-tls-webpki-roots = [
    "__rustls",
    "reqwest/rustls",
    "dep:rustls",
    "dep:webpki-roots",
]

# Internal features - these are not meant to be used by end users
__rustls = []

[dependencies]
log = "0.4"
oauth2 = { version = "5.0", default-features = false }
open = "5.3"
reqwest = { version = "0.13", default-features = false, features = [
    "blocking", "system-proxy",
] }
rustls = { version = "0.23", optional = true, default-features = false, features = ["aws_lc_rs", "std"] }
webpki-roots = { version = "1", optional = true }
http = "1"
thiserror = "2"
url = "2.5"

[dev-dependencies]
env_logger = { version = "0.11", default-features = false, features = [
    "color",
    "humantime",
    "auto-color",
] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
