[package]
name = "sotf-test-blas"
publish = false
version = "0.1.0"
edition = "2024"

[lib]
name = "test_blas"

[dependencies]

[build-dependencies]
infra = { version = "0.1.0", package = "sotf-infra", path = "../infra" }
itertools.workspace = true
lazy_static.workspace = true
suite-onnx = { version = "0.1.0", package = "sotf-suite-onnx", path = "../suite-onnx" }
suite-unit = { version = "0.1.0", package = "sotf-suite-unit", path = "../suite-unit" }
tract-core = { workspace = true, features = [ "blis" ] }

[dev-dependencies]
infra = { version = "0.1.0", package = "sotf-infra", path = "../infra" }
itertools.workspace = true
lazy_static.workspace = true
log.workspace = true
suite-onnx = { version = "0.1.0", package = "sotf-suite-onnx", path = "../suite-onnx" }
suite-unit = { version = "0.1.0", package = "sotf-suite-unit", path = "../suite-unit" }
tract-core = { workspace = true, features = [ "blis" ] }
tract-onnx-opl.workspace = true
